security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
            
        Demo\MediaBundle\Entity\User: 
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    providers:
        administrators:
            entity: { class: DemoMediaBundle:User, property: username }
#        in_memory:
#            memory:
#                users:
#                    admin: { password: d033e22ae348aeb5660fc2140aec35850c4da997, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /
#            http_basic:
#                realm: "My Media Manager"

    access_control:
        - { path: ^/media/, roles: ROLE_ADMIN }